services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-sqlserver
    environment:
      SA_PASSWORD: "#Test1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '#Test1234' -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: TaskFlow.API/Dockerfile
    container_name: taskflow-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TaskFlowDb: "Server=sqlserver;Database=TaskFlowDb;User Id=sa;Password=#Test1234;TrustServerCertificate=True;MultipleActiveResultSets=true"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver-data:
